# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'aruba', '2.2.0'
  gem 'cucumber', '9.2.0'
  gem 'rspec', '3.13.0'
  gem 'rubocop', '1.62.1'
  gem 'rubocop-rspec', '2.28.0'
end
