# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'aruba', '2.3.1'
  gem 'cucumber', '9.2.1'
  gem 'rspec', '3.13.1'
  gem 'rubocop', '1.80.2'
  gem 'rubocop-rspec', '3.6.0'
end
