version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  allow:
  - dependency-type: "all"
  schedule:
    interval: "weekly"
  groups:
    dev-non-major:
      dependency-type: development
      update-types:
      - patch
      - minor
    prod-patch:
      dependency-type: production
      update-types:
      - patch
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "bundler"
  directory: "test"
  allow:
  - dependency-type: "all"
  schedule:
    interval: "weekly"
  groups:
    # TODO: Can't we merge the two groups?
    test-dev-non-major:
      dependency-type: development
      update-types:
      - patch
      - minor
    test-prod-non-major:
      dependency-type: production
      update-types:
      - patch
      - minor
