version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  open-pull-requests-limit: 0
  labels:
  - "no changelog"
  commit-message:
    prefix: "chore"
    include: "scope"
- package-ecosystem: "github-actions"
  directory: "/"
  open-pull-requests-limit: 0
  labels:
  - "no changelog"
  commit-message:
    prefix: "chore"
    include: "scope"
- package-ecosystem: "bundler"
  directory: "test"
  open-pull-requests-limit: 0
  labels:
  - "no changelog"
  commit-message:
    prefix: "chore"
    include: "scope"
