---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.411.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cocogitto/cocogitto@6.3.0
- name: editorconfig-checker/editorconfig-checker@v3.4.0
- name: evilmartians/lefthook@v1.12.4
- name: golangci/golangci-lint@v1.64.8
- name: goreleaser/goreleaser@v1.26.2
- name: miniscruff/changie@v1.22.1
