---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.265.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cocogitto/cocogitto@6.1.0
- name: editorconfig-checker/editorconfig-checker@v3.0.3
- name: evilmartians/lefthook@v1.11.13
- name: golangci/golangci-lint@v1.61.0
- name: goreleaser/goreleaser@v1.26.2
- name: miniscruff/changie@v1.21.0
