# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
- format: binary

changelog:
  # disable: false # TODO: switch with goreleaser >=1.24
  skip: false

release:
  draft: true
  replace_existing_draft: true
