rc: .config/lefthook.rc

pre-commit:
  piped: true
  commands:
    formatter:
      priority: 1
      glob: "*.go"
      run: go fmt ./...
      stage_fixed: true
    vet:
      priority: 1
      glob: "*.go"
      # NB: go vet takes only files from a single directory
      #     s.a. https://github.com/evilmartians/lefthook/discussions/631
      run: for f in {staged_files}; do go vet "./$(dirname "${f}")"; done
    editorconfig:
      priority: 2
      exclude: '(^.idea/)|(\.(lock|go)$|(^go\.))'
      run: editorconfig-checker {staged_files}
commit-msg:
  commands:
    cog:
      run: cog verify --file {1}
post-checkout:
  commands:
    update_deps_go:
      glob: go.*
      run: go mod tidy
