rc: .config/lefthook.rc

pre-commit:
  piped: true
  commands:
    format_go:
      priority: 1
      glob: "*.go"
      run: go fmt ./...
      stage_fixed: true
    editorconfig:
      priority: 1
      exclude: '(^.run/)|(\.(lock|go)$|(^go\.))'
      run: editorconfig-checker {staged_files}
    lint_go:
      priority: 2
      glob: "*.go"
      # NB: go linter takes only files from a single directory
      #     s.a. https://github.com/evilmartians/lefthook/discussions/631
      run: for f in {staged_files}; do golangci-lint run "./$(dirname "${f}")"; done
    lint_ruby:
      priority: 2
      root: test
      glob: "*.rb"
      run: bundle exec rubocop {staged_files}
commit-msg:
  commands:
    cog:
      run: cog verify --file {1}
post-checkout:
  commands:
    update_deps_go:
      glob: go.*
      run: go mod tidy
    update_deps_ruby:
      root: test
      glob: "Gemfile.lock"
      run: bundle install
