name: Trigger Release

on:
  push:
    tags:
    - v*

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    # TODO: test again?

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5.0.0
      with:
        version: latest
        args: --clean --release-notes=.changes/${{ github.ref_name }}.md --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
